#version 450 core
#extension GL_EXT_control_flow_attributes : require

#include "vkllm_shader_header.comp.h"

layout(binding = 0) readonly buffer in0_type
{
    float in0[];
};

layout(binding = 1) readonly buffer in1_type
{
    float in1[];
};

layout(binding = 2) writeonly buffer out0_type
{
    float out0[];
};

layout(push_constant) uniform constants
{
    uint in0_stride;
    uint in1_stride;
    uint out0_stride;
    uint M; // in0.shape = [M, K], in1.shape = [K, N], out0.shape = [M, N]
    uint N;
    uint K;
};

// 每个workgroup计算一个C矩阵中的[BM, BN]块
// 每轮迭代计算一个 [BM, BK] * [BK, BN]的块，一共计算 K / BK轮迭代
// 即，每轮迭代加载 [BM, BK]个A矩阵，和[BK, BN]个B矩阵元素
// 每个thread计算一个 [TM, TN]块
// 也就是一个workgroup中包含 BM / TM * BN/TN个线程, work group size设置成(16, 16)

#define BM 128
#define BN 128
#define BK 8
#define TM 8
#define TN 8

#define SMEM_BK (BK / 4)
shared vec4 smem_a[BM][SMEM_BK];
shared vec4 smem_b[BN][SMEM_BK];

#define load_n_per_thread 4

// work group size = (1, 1, 256)

void main(void)
{
    // workgroup size = 256, smem_a.size = 1024
    // 每个线程加载4个元素
    uint blk_id_x = gl_WorkGroupID.x;
    uint blk_id_y = gl_WorkGroupID.y;

    uint local_tid_x = gl_LocalInvocationID.x;
    uint local_tid_y = gl_LocalInvocationID.y;
    uint tid = local_tid_x * gl_WorkGroupSize.y + local_tid_y;

    uint blk_tid = tid * load_n_per_thread;
    uint ld_a_x = blk_tid / BK; // tid * 4 / BK
    uint ld_a_y = blk_tid % BK;

    uint ld_b_x = (tid / BN) * load_n_per_thread;
    uint ld_b_y = (tid % BN);

    float thread_results[TM][TN]; // FIXME: clean

    [[unroll]] for (uint i = 0; i < TM; ++i)
    {
        [[unroll]] for (uint j = 0; j < TN; ++j)
        {
            thread_results[i][j] = .0;
        }
    }

    uint blk_x = blk_id_x * BM;
    uint blk_y = blk_id_y * BN;

    for (uint k = 0; k < (K + BK - 1) / BK; k += 1)
    {
        // Load data from global memory to shared memory
        uint a_row = blk_x + ld_a_x;
        uint a_col = k * BK + ld_a_y;
        uint smem_a_idx = a_row * in0_stride + a_col;

        if (a_row < M)
        {
            smem_a[ld_a_x][ld_a_y / 4] =
                vec4(in0[smem_a_idx], in0[smem_a_idx + 1], in0[smem_a_idx + 2], in0[smem_a_idx + 3]);
        }
        else
        {
            smem_a[ld_a_x][ld_a_y / 4] = vec4(0);
        }

        uint b_row = k * BK + ld_b_x;
        uint b_col = blk_y + ld_b_y;
        uint smem_b_idx = b_row * in1_stride + b_col;

        smem_b[ld_b_y][ld_b_x / load_n_per_thread] = vec4(.0);
        if (b_col < N)
        {
            if (b_row + 3 < K)
            {
                smem_b[ld_b_y][ld_b_x / load_n_per_thread] =
                    vec4(in1[smem_b_idx], in1[smem_b_idx + in1_stride], in1[smem_b_idx + 2 * in1_stride],
                         in1[smem_b_idx + 3 * in1_stride]);
            }
            else if (b_row + 2 < K)
            {
                smem_b[ld_b_y][ld_b_x / load_n_per_thread] =
                    vec4(in1[smem_b_idx], in1[smem_b_idx + in1_stride], in1[smem_b_idx + 2 * in1_stride], 0.0);
            }
            else if (b_row + 1 < K)
            {
                smem_b[ld_b_y][ld_b_x / load_n_per_thread] =
                    vec4(in1[smem_b_idx], in1[smem_b_idx + in1_stride], 0.0, 0.0);
            }
            else if (b_row < K)
            {
                smem_b[ld_b_y][ld_b_x / load_n_per_thread] = vec4(in1[smem_b_idx], 0.0, 0.0, 0.0);
            }
        }

        memoryBarrierShared();
        barrier();

        // 每个线程使用smem中的[TM, BK]和smem_b中的[BK, TN]个元素计算得到[TM, TN]个结果;
        for (uint tk = 0; tk < SMEM_BK; ++tk)
        {
            for (uint r = 0; r < TM; ++r)
            {
                for (uint c = 0; c < TN; ++c)
                {
                    vec4 a = smem_a[local_tid_x * TM + r][tk];
                    vec4 b = smem_b[local_tid_y * TN + c][tk];
                    thread_results[r][c] =
                        fma(a.x, b.x, fma(a.y, b.y, fma(a.z, b.z, fma(a.w, b.w, thread_results[r][c]))));
                }
            }
        }

        memoryBarrierShared();
        barrier();
    }

    // Write results back to global memory
    [[unroll]] for (uint tm = 0; tm < TM; ++tm)
    {
        [[unroll]] for (uint tn = 0; tn < TN; ++tn)
        {
            uint out_row = blk_x + local_tid_x * TM + tm;
            uint out_col = blk_y + local_tid_y * TN + tn;
            if (out_row < M && out_col < N)
            {
                out0[out_row * out0_stride + out_col] = thread_results[tm][tn];
            }
        }
    }
}
