#version 450 core
#extension GL_EXT_control_flow_attributes : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#ifdef _SUPPORT_FLOAT16_ARITHMETIC
#extension GL_EXT_shader_subgroup_extended_types_float16 : require
#endif

#include "vkllm_shader_header.comp.h"

layout(binding = 0) readonly buffer in0_type
{
    DTYPE in_vec[];
};

layout(binding = 1) readonly buffer in1_type
{
    DTYPE in_mat[];
};

layout(binding = 2) writeonly buffer out0_type
{
    DTYPE out_mat[];
};

layout(push_constant) uniform constants
{
    ShapeConstant shape_vec;
    ShapeConstant shape_mat;
    ShapeConstant shape_out;

    float scale;
    int act;
};

#define BOARDCAST_AXIS0 0
#define BOARDCAST_AXIS1 1
#define BOARDCAST_AXIS01 2
#define BOARDCAST_NONE 3

layout(constant_id = 0) const int a_boardcast_type = 0;
layout(constant_id = 1) const int b_boardcast_type = 0;

void get_indices(uint tid, out uint b, out uint c, out uint h, out uint w)
{
    uint shape3 = shape_out.shapes[3] / 4;
    uint cn = shape_out.shapes[2] * shape3;
    uint bn = shape_out.shapes[1] * cn;

    b = tid / bn;
    uint b_offset = b * bn;

    c = (tid - b_offset) / cn;
    uint c_offset = c * cn;

    h = (tid - b_offset - c_offset) / shape3;
    w = tid - b_offset - c_offset - h * shape3;
}

void get_batch_offset(uint b, uint c, out uint a_batch_offset, out uint b_batch_offset)
{
    a_batch_offset = 0;
    b_batch_offset = 0;
    if (a_boardcast_type == BOARDCAST_AXIS0)
    {
        a_batch_offset = c * shape_vec.strides[1];
    }
    else if (a_boardcast_type == BOARDCAST_AXIS1)
    {
        a_batch_offset = b * shape_vec.strides[0];
    }
    else if (a_boardcast_type == BOARDCAST_NONE)
    {
        a_batch_offset = b * shape_vec.strides[0] + c * shape_vec.strides[1];
    }

    if (b_boardcast_type == BOARDCAST_AXIS0)
    {
        b_batch_offset = c * shape_mat.strides[1];
    }
    else if (b_boardcast_type == BOARDCAST_AXIS1)
    {
        b_batch_offset = b * shape_mat.strides[0];
    }
    else if (b_boardcast_type == BOARDCAST_NONE)
    {
        b_batch_offset = b * shape_mat.strides[0] + c * shape_mat.strides[1];
    }
}

// subgroup size = 32, 每个subgroup负责计算输出 NUM_ROWS行 x NUM_COLS列的数据，也就是一个tile size = [NUM_ROWS,
// NUM_COLS]

void main()
{
    uint tid = get_thread_id();
    uint glb_subgroup_id = tid / gl_SubgroupSize;
    uint b = 0, c = 0, h = 0, w = 0;
    get_indices(glb_subgroup_id, b, c, h, w);

    if (b >= shape_out.shapes[0] || c >= shape_out.shapes[1] || h >= shape_out.shapes[2] ||
        4 * w >= shape_out.shapes[3])
    {
        return;
    }

    uint a_batch_off, b_batch_off;
    get_batch_offset(b, c, a_batch_off, b_batch_off);

    uint out_batch_off = b * shape_out.strides[0] + c * shape_out.strides[1];

    ACC_DTYPE acc[4] = {ACC_DTYPE(0), ACC_DTYPE(0), ACC_DTYPE(0), ACC_DTYPE(0)};

    uint K = shape_vec.shapes[3];
    uint a_glb_offs = a_batch_off + h * shape_vec.strides[2];

    uint iter_stride = 8 * gl_SubgroupSize;

    for (uint wi = 0; wi < 4; ++wi)
    {
        uint b_glb_offs = b_batch_off + (4 * w + wi) * shape_mat.strides[2];
        
        uint i = 8 * gl_SubgroupInvocationID.x;

        for (; i < K; i += iter_stride)
        {
            for (uint ii = 0; ii < 8; ++ii)
            {
                uint a0 = a_glb_offs + (i + ii) * shape_vec.strides[3];
                uint b0 = b_glb_offs + (i + ii) * shape_mat.strides[3];
                acc[wi] = fma(ACC_DTYPE(in_vec[a0]), ACC_DTYPE(in_mat[b0]), acc[wi]);
            }
        }

        for (; i < K; i += gl_SubgroupSize)
        {
            uint a0 = a_glb_offs + i * shape_vec.strides[3];
            uint b0 = b_glb_offs + i * shape_mat.strides[3];
            acc[wi] = fma(ACC_DTYPE(in_vec[a0]), ACC_DTYPE(in_mat[b0]), acc[wi]);
        }
    }

    for (uint wi = 0; wi < 4; ++wi)
    {
        uint ci = out_batch_off + h * shape_out.strides[2] + (4 * w + wi) * shape_out.strides[3];
        ACC_DTYPE v = subgroupAdd(acc[wi]) * ACC_DTYPE(scale);
        v = act == 1 ? v / (ACC_DTYPE(1.0) + exp(-v)) : v;
        if (subgroupElect())
        {
            out_mat[ci] = OUT_DTYPE(v);
        }
    }
}
