#version 450 core
#include "vkllm_shader_header.comp.h"

layout(binding = 0) readonly buffer kv_type
{
    DTYPE kv[];
};

layout(binding = 1) writeonly buffer kv_type1
{
    DTYPE kv_out[];
};

layout(push_constant) uniform constants
{
    ShapeConstant in_shape;
    ShapeConstant out_shape;
    uint offsets;
    LOAD_DTYPE base;
};

layout(constant_id = 0) const int neox_style = 0;

void get_indices(uint tid, out uint b, out uint c, out uint h, out uint w)
{
    uint shape3 = in_shape.shapes[3] / 2;
    uint cn = in_shape.shapes[2] * shape3;
    uint bn = in_shape.shapes[1] * cn;
    b = tid / bn;
    uint b_offset = b * bn;

    c = (tid - b_offset) / cn;
    uint c_offset = c * cn;

    h = (tid - b_offset - c_offset) / shape3;
    w = tid - b_offset - c_offset - h * shape3;
}

void main(void)
{
    uint tid = get_thread_id();
    uint b = 0, c = 0, h = 0, w = 0;
    get_indices(tid, b, c, h, w);

    if (b >= in_shape.shapes[0] || c >= in_shape.shapes[1] || h >= in_shape.shapes[2] || 2 * w >= in_shape.shapes[3])
    {
        return;
    }

    uint i0 = 0, i1 = 0, o0 = 0, o1 = 0;

    if (neox_style > 0)
    {
        i0 = b * in_shape.strides[0] + c * in_shape.strides[1] + h * in_shape.strides[2] + w * in_shape.strides[3];
        i1 = i0 + in_shape.strides[3] * in_shape.shapes[3] / 2;
        o0 = b * out_shape.strides[0] + c * out_shape.strides[1] + h * out_shape.strides[2] + w * out_shape.strides[3];
        o1 = o0 + out_shape.strides[3] * out_shape.shapes[3] / 2;
    }
    else
    {
        i0 = b * in_shape.strides[0] + c * in_shape.strides[1] + h * in_shape.strides[2] + 2 * w * in_shape.strides[3];
        i1 = i0 + in_shape.strides[3];
        o0 = b * out_shape.strides[0] + c * out_shape.strides[1] + h * out_shape.strides[2] +
             2 * w * out_shape.strides[3];
        o1 = o0 + out_shape.strides[3];
    }

    LOAD_DTYPE f = LOAD_DTYPE(offsets + h) / pow(base, LOAD_DTYPE(2 * w) / LOAD_DTYPE(in_shape.shapes[3]));
    LOAD_DTYPE freqc = cos(f);
    LOAD_DTYPE freqs = sin(f);

    LOAD_DTYPE v0 = LOAD_DTYPE(kv[i0]);
    LOAD_DTYPE v1 = LOAD_DTYPE(kv[i1]);
    LOAD_DTYPE q0 = freqc * v0 - freqs * v1;
    LOAD_DTYPE q1 = freqs * v0 + freqc * v1;

    kv_out[o0] = DTYPE(q0);
    kv_out[o1] = DTYPE(q1);
}
