#version 450 core
#include "vkllm_shader_header.comp.h"

layout(binding = 0) readonly buffer kv_type
{
    DTYPE kv[];
};

layout(binding = 1) writeonly buffer kv_type1
{
    DTYPE kv_out[];
};

layout(push_constant) uniform constants
{
    ShapeConstant kv_shape;
    uint offsets;
    LOAD_DTYPE base;
};

void get_indices(uint tid, out uint b, out uint c, out uint h, out uint w)
{
    uint shape3 = kv_shape.shapes[3] / 2;
    uint cn = kv_shape.shapes[2] * shape3;
    uint bn = kv_shape.shapes[1] * cn;
    b = tid / bn;
    uint b_offset = b * bn;

    c = (tid - b_offset) / cn;
    uint c_offset = c * cn;

    h = (tid - b_offset - c_offset) / shape3;
    w = tid - b_offset - c_offset - h * shape3;
}

void main(void)
{
    uint tid = get_thread_id();
    uint b = 0, c = 0, h = 0, w = 0;
    get_indices(tid, b, c, h, w);

    if (b >= kv_shape.shapes[0] || c >= kv_shape.shapes[1] || h >= kv_shape.shapes[2] || 2 * w >= kv_shape.shapes[3])
    {
        return;
    }

    uint i0 = b * kv_shape.strides[0] + c * kv_shape.strides[1] + h * kv_shape.strides[2] + 2 * w * kv_shape.strides[3];
    uint i1 = i0 + 1;

    LOAD_DTYPE f = LOAD_DTYPE(offsets + h) / pow(base, LOAD_DTYPE(2 * w) / LOAD_DTYPE(kv_shape.shapes[3]));
    LOAD_DTYPE freqc = cos(f);
    LOAD_DTYPE freqs = sin(f);

    LOAD_DTYPE v0 = LOAD_DTYPE(kv[i0]);
    LOAD_DTYPE v1 = LOAD_DTYPE(kv[i1]);
    LOAD_DTYPE o0 = freqc * v0 - freqs * v1;
    LOAD_DTYPE o1 = freqs * v0 + freqc * v1;

    kv_out[i0] = DTYPE(o0);
    kv_out[i1] = DTYPE(o1);
}
