#version 450 core
#include "vkllm_shader_header.comp.h"

layout(binding = 0) readonly buffer in0_type
{
    DTYPE in0[];
};

layout(binding = 1) writeonly buffer out0_type
{
    uint out0[];
};

layout(push_constant) uniform constants
{
    ShapeConstant shape0;
    ShapeConstant shape1;
    ShapeConstant shape2;
};

#define WORKGROUP_SIZE 32
#define FLT_MAX 3.402823466e+38F

void get_indices(uint tid, out uint b, out uint c, out uint h)
{
    uint shape3 = WORKGROUP_SIZE;
    uint cn = shape0.shapes[2] * shape3;
    uint bn = shape0.shapes[1] * cn;
    b = tid / bn;
    uint b_offset = b * bn;

    c = (tid - b_offset) / cn;
    uint c_offset = c * cn;

    h = (tid - b_offset - c_offset) / shape3;
}

shared LOAD_DTYPE max_vals[WORKGROUP_SIZE];
shared uint max_indices[WORKGROUP_SIZE];

void main(void)
{
    uint tid = get_thread_id();
    uint b, c, h;
    get_indices(tid, b, c, h);

    if (b >= shape0.shapes[0] || c >= shape0.shapes[1] || h >= shape0.shapes[2])
    {
        return;
    }

    uint local_w = gl_LocalInvocationID.x;
    uint glb_offs = b * shape0.strides[0] + c * shape0.strides[1] + h * shape0.strides[2];

    LOAD_DTYPE max_val = LOAD_DTYPE(-FLT_MAX);
    uint max_idx = local_w;
    if (local_w < shape0.shapes[3])
    {
        max_val = LOAD_DTYPE(in0[glb_offs + local_w]);
    }

    for (uint i = local_w + WORKGROUP_SIZE; i < shape0.shapes[3]; i += WORKGROUP_SIZE)
    {
        LOAD_DTYPE val = LOAD_DTYPE(in0[glb_offs + i]);
        if (val > max_val)
        {
            max_val = val;
            max_idx = i;
        }
    }

    max_vals[local_w] = max_val;
    max_indices[local_w] = max_idx;

    memoryBarrierShared();
    barrier();

    for (int i = int(WORKGROUP_SIZE) / 2; i > 0; i >>= 1)
    {
        if (local_w < i)
        {
            if (max_vals[local_w + i] > max_vals[local_w])
            {
                max_vals[local_w] = max_vals[local_w + i];
                max_indices[local_w] = max_indices[local_w + i];
            }
        }

        memoryBarrierShared();
        barrier();
    }

    if (local_w == 0)
    {
        uint out0_i = b * shape1.strides[0] + c * shape1.strides[1] + h * shape1.strides[2];
        out0[out0_i] = max_indices[0];
    }
}
