#version 450 core
#extension GL_EXT_control_flow_attributes : require

#include "vkllm_shader_header.comp.h"

#ifndef IN0_DTYPE
#define IN0_DTYPE float
#endif

#ifndef IN1_DTYPE
#define IN1_DTYPE float
#endif

#ifndef OUT_DTYPE
#define OUT_DTYPE float
#endif

#ifndef SMEM_VEC2
#define SMEM_VEC2 vec2
#endif

#ifndef LOAD_DTYPE
#define LOAD_DTYPE
#endif

layout(binding = 0) readonly buffer in0_type
{
    IN0_DTYPE in0[];
};

layout(binding = 1) readonly buffer in1_type
{
    IN1_DTYPE in1[];
};

layout(binding = 2) writeonly buffer out0_type
{
    OUT_DTYPE out0[];
};

layout(constant_id = 0) const int a_boardcast_type = 0;
layout(constant_id = 1) const int b_boardcast_type = 0;
layout(constant_id = 2) const uint BM = 64;
layout(constant_id = 3) const uint BN = 64;
layout(constant_id = 4) const uint BK = 8;
layout(constant_id = 5) const uint TM = 4;
layout(constant_id = 6) const uint TN = 4;
layout(constant_id = 7) const uint load_n_per_thread = 2;

layout(push_constant) uniform constants
{
    uint in0_stride;
    uint in1_stride;
    uint out0_stride;

    uint in0_bstride;
    uint in1_bstride;
    uint out0_bstride;

    uint in0_cstride;
    uint in1_cstride;
    uint out0_cstride;

    uint B;
    uint C;
    uint M; // in0.shape = [M, K], in1.shape = [K, N], out0.shape = [M, N]
    uint N;
    uint K;

    float scale;
    int act;
};

// 每个workgroup计算一个C矩阵中的[BM, BN]块
// 每轮迭代计算一个 [BM, BK] * [BK, BN]的块，一共计算 K / BK轮迭代
// 即，每轮迭代加载 [BM, BK]个A矩阵，和[BK, BN]个B矩阵元素
// 每个thread计算一个 [TM, TN]块
// 也就是一个workgroup中包含 BM / TM * BN/TN个线程, work group size设置成(16, 16)

#define SMEM_BK (BK / 2)

shared SMEM_VEC2 smem_a[BM][SMEM_BK + 1];
shared SMEM_VEC2 smem_b[BN][SMEM_BK + 1];

#define BOARDCAST_AXIS0 0
#define BOARDCAST_AXIS1 1
#define BOARDCAST_AXIS01 2
#define BOARDCAST_NONE 3

// work group size = (1, 1, 256)

void main(void)
{
    // workgroup size = 16 * 16 = 256, smem_a.size = BM * BK = 64 * 8 = 512
    // 每个线程加载2个元素
    uint blk_id_x = gl_WorkGroupID.x;
    uint blk_id_y = gl_WorkGroupID.y;

    uint local_tid_x = gl_LocalInvocationID.x;
    uint local_tid_y = gl_LocalInvocationID.y;
    uint tid = local_tid_x * gl_WorkGroupSize.y + local_tid_y;

    uint glb_tid_z = gl_GlobalInvocationID.z;
    uint batch_id = glb_tid_z / C;
    uint channel_id = glb_tid_z % C;

    // uint a_batch_off = BOARDCAST_AXIS01;
    uint a_batch_off = 0;
    if (a_boardcast_type == BOARDCAST_AXIS0)
    {
        a_batch_off = channel_id * in0_cstride;
    }
    else if (a_boardcast_type == BOARDCAST_AXIS1)
    {
        a_batch_off = batch_id * in0_bstride;
    }
    else if (a_boardcast_type == BOARDCAST_NONE)
    {
        a_batch_off = batch_id * in0_bstride + channel_id * in0_cstride;
    }

    uint b_batch_off = 0;

    if (b_boardcast_type == BOARDCAST_AXIS0)
    {
        b_batch_off = channel_id * in1_cstride;
    }
    else if (b_boardcast_type == BOARDCAST_AXIS1)
    {
        b_batch_off = batch_id * in1_bstride;
    }
    else if (b_boardcast_type == BOARDCAST_NONE)
    {
        b_batch_off = batch_id * in1_bstride + channel_id * in1_cstride;
    }

    uint out_batch_off = batch_id * out0_bstride + channel_id * out0_cstride;

    uint blk_tid = tid * load_n_per_thread;
    uint ld_a_x = blk_tid / BK; // tid * 4 / BK
    uint ld_a_y = blk_tid % BK;

    uint ld_b_x = (tid / BN) * load_n_per_thread;
    uint ld_b_y = (tid % BN);

    float thread_results[TM][TN]; // FIXME: clean

    [[unroll]] for (uint i = 0; i < TM; ++i)
    {
        [[unroll]] for (uint j = 0; j < TN; ++j)
        {
            thread_results[i][j] = .0;
        }
    }

    uint blk_x = blk_id_x * BM;
    uint blk_y = blk_id_y * BN;

    for (uint k = 0; k < (K + BK - 1) / BK; k += 1)
    {
        // Load data from global memory to shared memory
        uint a_row = blk_x + ld_a_x;
        uint a_col = k * BK + ld_a_y;
        uint smem_a_idx = a_batch_off + a_row * in0_stride + a_col;

        smem_a[ld_a_x][ld_a_y / 2] = SMEM_VEC2(0);
        if (a_row < M)
        {
            if (a_col + 1 < K)
            {
                smem_a[ld_a_x][ld_a_y / 2] = SMEM_VEC2(LOAD_DTYPE(in0[smem_a_idx]), LOAD_DTYPE(in0[smem_a_idx + 1]));
            }
            else if (a_col < K)
            {
                smem_a[ld_a_x][ld_a_y / 2] = SMEM_VEC2(LOAD_DTYPE(in0[smem_a_idx]), LOAD_DTYPE(0));
            }
        }

        uint b_row = k * BK + ld_b_x;
        uint b_col = blk_y + ld_b_y;
        uint smem_b_idx = b_batch_off + b_row * in1_stride + b_col;

        smem_b[ld_b_y][ld_b_x / 2] = SMEM_VEC2(0);
        if (b_col < N)
        {
            if (b_row + 1 < K)
            {
                smem_b[ld_b_y][ld_b_x / load_n_per_thread] =
                    SMEM_VEC2(LOAD_DTYPE(in1[smem_b_idx]), LOAD_DTYPE(in1[smem_b_idx + in1_stride]));
            }
            else if (b_row < K)
            {
                smem_b[ld_b_y][ld_b_x / load_n_per_thread] = SMEM_VEC2(LOAD_DTYPE(in1[smem_b_idx]), LOAD_DTYPE(0));
            }
        }

        memoryBarrierShared();
        barrier();

        // 每个线程使用smem中的[TM, BK]和smem_b中的[BK, TN]个元素计算得到[TM, TN]个结果;
        [[unroll]] for (uint tk = 0; tk < SMEM_BK; ++tk)
        {
            [[unroll]] for (uint tr = 0; tr < 2; ++tr)
            {
                SMEM_VEC2 cache_a[TM / 2];
                uint R = tr * TM / 2;
                uint smem_b_off = local_tid_y * TN;
                uint smem_a_off = local_tid_x * TM + R;
                [[unroll]] for (uint r = 0; r < TM / 2; ++r)
                {
                    cache_a[r] = smem_a[smem_a_off + r][tk];
                }

                [[unroll]] for (uint r = 0; r < TM / 2; ++r)
                {
                    [[unroll]] for (uint c = 0; c < TN; ++c)
                    {
                        thread_results[R + r][c] += float(dot(cache_a[r], smem_b[smem_b_off + c][tk]));
                    }
                }
            }
        }

        memoryBarrierShared();
        barrier();
    }

    // Write results back to global memory
    [[unroll]] for (uint tm = 0; tm < TM; ++tm)
    {
        [[unroll]] for (uint tn = 0; tn < TN; ++tn)
        {
            uint out_row = blk_x + local_tid_x * TM + tm;
            uint out_col = blk_y + local_tid_y * TN + tn;
            uint off = out_batch_off + out_row * out0_stride;
            float val = thread_results[tm][tn] * scale;
            val = act == 1 ? val / (1.0 + exp(-val)) : val;

            if (out_row < M && out_col < N)
            {
                out0[off + out_col] = OUT_DTYPE(val);
            }
        }
    }
}
