#version 450 core
#include "vkllm_shader_header.comp.h"

layout(binding = 0) readonly buffer in0_type
{
    DTYPE in0[];
};

layout(binding = 1) writeonly buffer out0_type
{
    DTYPE out0[];
};

layout(push_constant) uniform constants
{
    ShapeConstant shape0;
    ShapeConstant shape1;
};

void get_indices(uint tid, out uint b, out uint c, out uint h, out uint w)
{
    uint shape3 = shape0.shapes[3];
    uint cn = shape0.shapes[2] * shape3;
    uint bn = shape0.shapes[1] * cn;
    b = tid / bn;
    uint b_offset = b * bn;

    c = (tid - b_offset) / cn;
    uint c_offset = c * cn;

    h = (tid - b_offset - c_offset) / shape3;
    w = tid - b_offset - c_offset - h * shape3;
}

void main(void)
{
    uint tid = get_thread_id();
    uint b = 0, c = 0, h = 0, w = 0;
    get_indices(tid, b, c, h, w);

    if (b >= shape0.shapes[0] || c >= shape0.shapes[1] || h >= shape0.shapes[2] || w >= shape0.shapes[3])
    {
        return;
    }

    uint i0 = b * shape0.strides[0] + c * shape0.strides[1] + h * shape0.strides[2] + w * shape0.strides[3];
    uint o0 = b * shape1.strides[0] + c * shape1.strides[1] + h * shape1.strides[2] + w * shape1.strides[3];

    out0[o0] = in0[i0];
}
