cc_test(
    name = "test_new_gpu",
    srcs = ["test_new_gpu.c"],
    deps = [
        "//src:core",
    ],
    copts = [
        "-std=c11",
    ],
)

cc_test(
    name = "test_transfer",
    srcs = ["test_transfer.c"],
    deps = [
        "//src:core",
    ],
    copts = [
        "-std=c11",
    ],
)

cc_test(
    name = "test_vector_add",
    srcs = ["test_vector_add.c"],
    deps = [
        "//src:core",
        "//src:ops",
    ],
    copts = [
        "-std=c11",
    ],
)
