cc_library(
    name = "vkllm_llama2_layers",
    srcs = [
        "vkllm_llama2_layers.c",
    ],
    hdrs = [
        "vkllm_llama2_layers.h",
    ],
    deps = [
        "//src/core:core",
    ],
    copts = [
        "-std=c11"
    ],

    linkstatic = True,
    visibility = ["//visibility:public"],
)
