cc_library(
    name = "core",
    srcs = [
        "gpu_device.c",
    ],
    hdrs = [
        "gpu_device.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
		"//vulkan_rules:vulkan_cc_library",
    ]
)
